### ISSUE TITLE
Build crash

### ISSUE THREAD

**Issue by lrtrln** [tomatophp/tomato-admin#2]
Hello tomato,
I wanted to test your admin but I have a crash right away when I run the command 
`npm run build`

> [vite]: Rollup failed to resolve import "vue3-swatches" from "vendor/tomatophp/tomato-components/resources/js/components/TomatoColor.vue".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
> error during build:
> Error: [vite]: Rollup failed to resolve import "vue3-swatches" from "vendor/tomatophp/tomato-components/resources/js/components/TomatoColor.vue".

**Comment by fadymondy** [comment]
try

php artisan tomato-components:install
yarn
yarn build

**Comment by lrtrln** [comment]
thank you for your reply.
exact same crash when installing tomato-components
and yarn / yarn build
(nodejs -v 16.19)

install process:
* new fresh laravel 9
* tomato-admin:install
* tomato-components:install
* yarn 
* yarn build or vite build or npm run build
and crash

**Comment by fadymondy** [comment]
okay I got the problem just install these packages and then build, we add this line to the docs

```bash
yarn add vue3-editor codemirror-editor-vue3 vue3-tel-input vue3-swatches vue-draggable-next @suadelabs/vue3-multiselect
```

```bash
yarn build
```
